name: dictionary
version: 0.0
author: "bnspalding"
copyright: "Copyright (c) 2019 Ben Spalding"
synopsis: "lexical dictionary: words, glosses, pronunciations, pos"
description: Please see the README on Github at <https://github.com/bnspalding/dictionary#readme>

dependencies:
  - base >= 4.9 && < 5
  - containers
  - sound
  - text
  - aeson
  - bytestring

library:
  source-dirs: src

executables:
  mk-dict:
    main: Main.hs
    source-dirs: mk-dict
    dependencies:
        - dictionary
        - optparse-applicative

tests:
  dictionary-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - dictionary
      - hspec

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

